global:
    scrape_interval: 15s
    evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['PORTAINER_IP:9090']
  - job_name: 'vmware-vcenter'
    #scrape_interval: 15s
    #scrape_timeout:  30s
    static_configs:
      - targets:
        - VSPHERE_IP
    metrics_path: /metrics
    params:
      section: [vcenter]

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: PORTAINER_IP:9272